### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by xxx871** [xxx871/sound_hit#35]
## 各種情報
サービス名：音ぴしゃ（おんぴしゃ）
サービスURL：https://sound-hit.vercel.app/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] プロフィール編集機能
- [x] 音域登録機能
- [x] 遊び方
- [x] 難易度・性別選択機能
- [x] ゲーム機能

READMEレビュー時にMVPリリース時点で実装予定だったが、issueカリキュラムの際にMVPリリース後の実装とした機能
- [ ] パスワードリセット機能
- [ ] ランキング掲載機能

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください

## サービスイメージがわかるようなスクリーンショット等
[![Image from Gyazo](https://i.gyazo.com/0fefda7b8e583d9fcce5998493e7b7cb.gif)](https://gyazo.com/0fefda7b8e583d9fcce5998493e7b7cb)

[![Image from Gyazo](https://i.gyazo.com/68e9659fdb3c63002344f92815e74e6f.gif)](https://gyazo.com/68e9659fdb3c63002344f92815e74e6f)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

**Comment by xxx871** [comment]
ありがとうございます！引き続きやってまいります！
