### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by xxx871** [xxx871/sound_hit#39]
### 実装予定の機能
* [ ] ユーザー登録
* [ ] ログイン
* [ ] 部外サービスでのユーザーログイン
* [ ] プロフィール編集
* [ ] 音域登録
* [ ] 音声認識機能
* [ ] 音声出力機能
* [ ] 音声判定機能

MVPリリース後
* [ ] パスワードリセット
* [ ] X共有
* [ ] テスト

### 必要なページ
* [ ] トップページ
* [ ] 遊び方（モーダル）
* [ ] ログイン
* [ ] サインアップ
* [ ] マイページ
* [ ] マイページ編集
* [ ] 音域チェック
* [ ] ゲーム準備画面
* [ ] プレイ画面
* [ ] リザルト画面

MVPリリース後
* [ ] ランキング
* [ ] 利用規約
* [ ] プライバシーポリシー
* [ ] お問い合わせ
* [ ] パスワードリセット
* [ ] ローディング画面
* [ ] 判定画面
* [ ] 音確認画面(追加サービス)
* [ ] ハモりモード(追加サービス)
* [ ] 連続音当て(追加サービス)

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。

--- 

Projectを確認させていただいたところ、ストーリポイントが5以上で設定されているissueがいくつか見受けられます。可能であれば、これらのissueはストーリーポイントが`3~1`になる様、さらに分解していissueを作成していただければと思います。

**Comment by xxx871** [comment]
ご確認・コメントくださりありがとうございます。
いくつかのissueについて、分割することでストーリーポイントを3以下へ、または参考サイトがある機能はストーリーポイントを5から3に引き下げました。
音声の入出力に関する機能はある程度実装の流れは考えておりますが、調査が及ばない箇所が出てくる可能性が他に比べても高いと考え、ストーリーポイントを5のままにしております。
再度ご確認よろしくお願いいたします、

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
以下コメントになります。

---

■MVPリリース語で良さそうなissue（別途列を用意してそちらに配置）
・利用規約
・プライバシーポリシー
・お問い合わせ
・パスワードリセット
・ランキング
・ローディング画面
・判定中画面
・X共有
・ファビコン
・共通レイアウトの調整
・RSpec
・Rubocop
